service: moja-aplikacja-serverless
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: dist/server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

package:
  individually: true

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
